# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.CharField(blank=True, choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], max_length=20, null=True)),
                ('type', models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rose', 'Rose'), ('Sparkling', 'Sparkling')], max_length=12)),
                ('variety', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Barbera', 'Barbera'), ('Blaufränkisch', 'Blaufränkisch'), ('Cabernet Franc', 'Cabernet Franc'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Carignan', 'Carignan'), ('Carménère', 'Carménère'), ('Chardonnay', 'Chardonnay'), ('Châteauneuf-du-Pape', 'Châteauneuf-du-Pape'), ('Chenin Blanc', 'Chenin Blanc'), ('Cinsault', 'Cinsault'), ('Colombard', 'Colombard'), ('Durif (Petite Sirah)', 'Durif (Petite Sirah)'), ('Gamay', 'Gamay'), ('Gewürztraminer', 'Gewürztraminer'), ('Glera (Prosecco)', 'Glera (Prosecco)'), ('Graciano', 'Graciano'), ('Granache/Garnacha', 'Granache/Garnacha'), ('Grüner Veltliner', 'Grüner Veltliner'), ('Malbec', 'Malbec'), ('Malvasía', 'Malvasía'), ('Marsanne', 'Marsanne'), ('Mataro', 'Mataro'), ('Maturana', 'Maturana'), ('Mazuelo', 'Mazuelo'), ('Merlot', 'Merlot'), ('Montepulciano', 'Montepulciano'), ('Muscat', 'Muscat'), ('Nebbiolo', 'Nebbiolo'), ("Nero d'Avola", "Nero d'Avola"), ('Petit Verdot', 'Petit Verdot'), ('Pinotage', 'Pinotage'), ('Pinot Blanc/Bianco', 'Pinot Blanc/Bianco'), ('Pinot Grigio', 'Pinot Grigio'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Meunier', 'Pinot Meunier'), ('Pinot Noir', 'Pinot Noir'), ('Riesling', 'Riesling'), ('Roussanne', 'Roussanne'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Sémillon', 'Sémillon'), ('Shiraz', 'Shiraz'), ('Syrah', 'Syrah'), ('Tempranillo', 'Tempranillo'), ('Trebbiano', 'Trebbiano'), ('Trollinger', 'Trollinger'), ('Viognier', 'Viognier'), ('Viura (Macabeo)', 'Viura (Macabeo)'), ('Zinfandel', 'Zinfandel')], max_length=100, null=True)),
                ('vintage', models.CharField(max_length=4)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('shop', models.CharField(blank=True, choices=[('Aldi', 'Aldi'), ('Asda', 'Asda'), ('Co-op', 'Co-op'), ("Laithwaite's", "Laithwaite's"), ('Lidl', 'Lidl'), ('M&S', 'M&S'), ('Majestic Wine', 'Majestic Wine'), ('Morrisons', 'Morrisons'), ('Ocado', 'Ocado'), ('Oddbins', 'Oddbins'), ("Sainsbury's", "Sainsbury's"), ('Tesco', 'Tesco'), ('Virgin Wines', 'Virgin Wines'), ('Waitrose', 'Waitrose')], max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
