# Generated by Django 2.0.6 on 2018-06-25 11:57

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('rating', models.CharField(blank=True, choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], max_length=20, null=True)),
                ('type', models.CharField(choices=[('Not Selected', 'Select type'), ('Red', 'Red'), ('White', 'White'), ('Rose', 'Rose'), ('Sparkling', 'Sparkling')], default='Select type', max_length=12)),
                ('variety', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cabernet Franc', 'Cabernet Franc'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Cinsault', 'Cinsault'), ('Granache', 'Granache'), ('Malbec', 'Malbec'), ('Merlot', 'Merlot'), ('Montepulciano', 'Montepulciano'), ("Nero d'Avola", "Nero d'Avola"), ('Prosecco', 'Prosecco'), ('Pinotage', 'Pinotage'), ('Pinot Grigio', 'Pinot Grigio'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Noir', 'Pinot Noir'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz', 'Shiraz'), ('Tempranillo', 'Tempranillo')], max_length=100, null=True)),
                ('vintage', models.CharField(max_length=4)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('shop', models.CharField(blank=True, choices=[('Aldi', 'Aldi'), ('Asda', 'Asda'), ('M&S', 'M&S'), ("Sainsbury's", "Sainsbury's"), ('Tesco', 'Tesco'), ('Virgin Wines', 'Virgin Wines'), ('Waitrose', 'Waitrose')], max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
