# Generated by Django 2.0.6 on 2018-06-25 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
        ),
    ]
