# Generated by Django 2.0.6 on 2018-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_wine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
