# Generated by Django 2.0.6 on 2018-06-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180625_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='slug',
        ),
    ]
