# Generated by Django 2.0.6 on 2018-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_wine_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('red', 'Red'), ('white', 'White'), ('rose', 'Rose'), ('sparkling', 'Sparkling')], default='red', max_length=9),
        ),
        migrations.AlterField(
            model_name='wine',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
