# Generated by Django 2.0.6 on 2018-06-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_wine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
