# Generated by Django 2.0.6 on 2018-06-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_wine_cultivar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='cultivar',
            field=models.CharField(choices=[('cabernet franc', 'Cabernet Franc'), ('cabernet sauvignon', 'Cabernet Sauvignon'), ('cinsault', 'Cinsault'), ('granache', 'Granache'), ('malbec', 'Malbec'), ('merlot', 'Merlot'), ('montepulciano', 'Montepulciano'), ("nero d'avola", "Nero d'Avola"), ('pinotage', 'Pinotage'), ('pinot grigio', 'Pinot Grigio'), ('pinot gris', 'Pinot Gris'), ('pinot noir', 'Pinot Noir'), ('sangiovese', 'Sangiovese'), ('sauvignon blanc', 'Sauvignon Blanc'), ('shiraz', 'Shiraz'), ('tempranillo', 'Tempranillo')], default='cabernet franc', max_length=20),
        ),
    ]
