# Generated by Django 2.0.6 on 2018-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180629_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
