# Generated by Django 2.0.6 on 2018-06-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_wine_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='slug',
        ),
    ]
