# Generated by Django 2.0.6 on 2018-07-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_wine_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='variety',
        ),
    ]
