# Generated by Django 2.0.6 on 2018-06-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_wine_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='cultivar',
            new_name='variety',
        ),
    ]
