# Generated by Django 2.0.6 on 2018-06-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180619_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='blog/media/default.jpeg', upload_to='blog/media'),
        ),
    ]
