# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_wine_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
