# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180703_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Rose', 'Rose'), ('Sparkling', 'Sparkling')], max_length=12),
        ),
    ]
