# Generated by Django 2.0.6 on 2018-06-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180620_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
