# Generated by Django 2.0.6 on 2018-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180620_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
