# Generated by Django 2.0.6 on 2018-06-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180621_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='type',
            field=models.CharField(choices=[('Not Selected', 'Select type'), ('Red', 'Red'), ('White', 'White'), ('Rose', 'Rose'), ('Sparkling', 'Sparkling')], default='Select type', max_length=12),
        ),
    ]
