# Generated by Django 2.0.6 on 2018-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20180621_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='variety',
            field=models.CharField(choices=[('Not Selected', 'Select grapes'), ('Cabernet Franc', 'Cabernet Franc'), ('Cabernet Sauvignon', 'Cabernet Sauvignon'), ('Cinsault', 'Cinsault'), ('Granache', 'Granache'), ('Malbec', 'Malbec'), ('Merlot', 'Merlot'), ('Montepulciano', 'Montepulciano'), ("Nero d'Avola", "Nero d'Avola"), ('Prosecco', 'Prosecco'), ('Pinotage', 'Pinotage'), ('Pinot Grigio', 'Pinot Grigio'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Noir', 'Pinot Noir'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz', 'Shiraz'), ('Tempranillo', 'Tempranillo')], default='Select grapes', max_length=20),
        ),
    ]
