# Generated by Django 2.0.6 on 2018-06-21 11:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180621_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='favourite_colour',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Red', 'Red1'), ('Blue', 'Blue1'), ('White', 'White1'), ('Green', 'Green1'), ('Yellow', 'Yellow1')], default=1, max_length=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wine',
            name='favourite_colours',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Red2'), (2, 'Blue2'), (3, 'White2'), (4, 'Green2'), (5, 'Yellow2')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
