# Generated by Django 2.0.6 on 2018-06-21 11:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180621_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='favourite_colours',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Red2'), (2, 'Blue2'), (3, 'White2'), (4, 'Green2'), (5, 'Yellow2')], max_length=5),
        ),
    ]
