# Generated by Django 2.0.6 on 2018-06-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180621_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='favourite_colour',
        ),
    ]
