# Generated by Django 2.0.6 on 2018-06-21 11:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_wine_favourite_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='favourite_colours',
        ),
        migrations.AddField(
            model_name='wine',
            name='grapes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Not Selected', 'Select grapes'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Noir', 'Pinot Noir'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz', 'Shiraz'), ('Tempranillo', 'Tempranillo')], default='Select grapes', max_length=20),
        ),
    ]
