# Generated by Django 2.0.6 on 2018-06-21 11:55

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180621_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Not Selected', 'Select grapes'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Noir', 'Pinot Noir'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz', 'Shiraz'), ('Tempranillo', 'Tempranillo')], default='Select grapes', max_length=100),
        ),
    ]
