# Generated by Django 2.0.6 on 2018-06-21 11:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180621_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Not Selected', 'Select grapes'), ('Pinot Gris', 'Pinot Gris'), ('Pinot Noir', 'Pinot Noir'), ('Sangiovese', 'Sangiovese'), ('Sauvignon Blanc', 'Sauvignon Blanc'), ('Shiraz', 'Shiraz'), ('Tempranillo', 'Tempranillo')], max_length=100, null=True),
        ),
    ]
