# Generated by Django 2.0.6 on 2018-06-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_wine_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.CharField(choices=[('None', '-----'), ('&#9734', 'Cabernet Sauvignon'), ('Two', 'Cinsault'), ('Three', 'Granache'), ('Four', 'Malbec'), ('Five', 'Malbec')], default='-----', max_length=5),
        ),
    ]
