# Generated by Django 2.0.6 on 2018-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20180625_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.CharField(choices=[('None', '-----'), ('★☆☆☆☆', 'One star'), ('★★☆☆☆', 'Two stars'), ('★★★☆☆', 'Three stars'), ('★★★★☆', 'Four stars'), ('★★★★★', 'Five stars')], default='-----', max_length=20),
        ),
    ]
