# Generated by Django 2.0.6 on 2018-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_auto_20180625_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wine',
            name='shop',
            field=models.CharField(blank=True, choices=[('None', '-----'), ('Aldi', 'Aldi'), ('Asda', 'Asda'), ('M&S', 'M&S'), ("Sainsbury's", "Sainsbury's"), ('Tesco', 'Tesco'), ('Virgin Wines', 'Virgin Wines'), ('Waitrose', 'Waitrose')], max_length=20, null=True),
        ),
    ]
