# Generated by Django 2.0.6 on 2018-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20180625_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.CharField(blank=True, choices=[('★☆☆☆☆', 'One star'), ('★★☆☆☆', 'Two stars'), ('★★★☆☆', 'Three stars'), ('★★★★☆', 'Four stars'), ('★★★★★', 'Five stars')], max_length=20, null=True),
        ),
    ]
