# Generated by Django 2.0.6 on 2018-06-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_auto_20180625_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='rating',
            field=models.CharField(blank=True, choices=[('★☆☆☆☆', 'One star'), ('★★☆☆☆', 'Two stars'), ('★★★☆☆', 'Three stars'), ('★★★★☆', 'Four stars'), ('★★★★★', 'Five stars')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='shop',
            field=models.CharField(blank=True, choices=[('Aldi', 'Aldi'), ('Asda', 'Asda'), ('M&S', 'M&S'), ("Sainsbury's", "Sainsbury's"), ('Tesco', 'Tesco'), ('Virgin Wines', 'Virgin Wines'), ('Waitrose', 'Waitrose')], max_length=20, null=True),
        ),
    ]
